name: mile_navigation_engine
description: Native custom Mapbox navigation for Mile projects.
version: 0.0.2
#author: "Lionel Malloggi <lionel.malloggi.mile@gmail.com>"
repository: "https://github.com/MapleNoise/mile_navigation_engine.git"
homepage: "https://www.mile.eu.com"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.mile.mile_navigation_engine
    pluginClass: MileNavigationEnginePlugin
